# Generated by Django 6.1 on 2026-08-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='marque')),
                ('image', models.ImageField(blank=True, null=True, upload_to='perfumes/', verbose_name='photo')),
                ('buy_price', models.PositiveIntegerField(verbose_name="prix d'achat (FCFA)")),
                ('sell_price', models.PositiveIntegerField(verbose_name='prix de vente (FCFA)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parfum',
                'verbose_name_plural': 'parfums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume_name', models.CharField(max_length=200, verbose_name='nom du parfum')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantité')),
                ('unit_sell_price', models.PositiveIntegerField(verbose_name='prix de vente unitaire (FCFA)')),
                ('unit_buy_price', models.PositiveIntegerField(verbose_name="prix d'achat unitaire (FCFA)")),
                ('date', models.DateField(verbose_name='date de vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='parfums.perfume', verbose_name='parfum')),
            ],
            options={
                'verbose_name': 'vente',
                'verbose_name_plural': 'ventes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
