# Generated by Django 6.1 on 2026-09-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfume',
            options={'ordering': ['name'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AddField(
            model_name='perfume',
            name='category',
            field=models.CharField(choices=[('parfums', 'Parfums'), ('chaussures', 'Chaussures'), ('electronique', 'Électronique'), ('autre', 'Autre')], default='parfums', max_length=20, verbose_name='catégorie'),
        ),
    ]
