# Generated by Django 6.1 on 2026-09-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfums', '0002_alter_perfume_options_perfume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.CharField(choices=[('parfums', 'Parfums'), ('chaussures', 'Chaussures'), ('electronique', 'Électronique'), ('autre', 'Autre')], default='parfums', max_length=20, verbose_name='catégorie'),
        ),
    ]
